# Generated by Django 3.0.5 on 2021-01-06 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdetails',
            name='section',
            field=models.CharField(blank=True, choices=[('A', 'A Section'), ('B', 'A Section'), ('C', 'A Section')], max_length=1),
        ),
    ]
