# Generated by Django 3.0.5 on 2021-01-06 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_studentdetails_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetails',
            name='section',
            field=models.CharField(blank=True, choices=[('A', 'A Section'), ('B', 'B Section'), ('C', 'C Section')], max_length=1),
        ),
    ]
