# Generated by Django 3.0.5 on 2021-01-03 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_models', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='8Qydqsrg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': '8QYDqsRg',
                'db_table': 'dynamic_models_8qydqsrg',
            },
        ),
        migrations.CreateModel(
            name='Abhilash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('something', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Abhilash',
                'db_table': 'dynamic_models_abhilash',
            },
        ),
        migrations.CreateModel(
            name='Abhilashs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abd', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Abhilashs',
                'db_table': 'dynamic_models_abhilashs',
            },
        ),
        migrations.CreateModel(
            name='Bttbqvxm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=20)),
                ('semester', models.CharField(max_length=20)),
                ('section', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'BTTbQVXm',
                'db_table': 'dynamic_models_bttbqvxm',
            },
        ),
        migrations.CreateModel(
            name='Bvmivam4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=20)),
                ('semester', models.CharField(max_length=20)),
                ('section', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'bvmiVAM4',
                'db_table': 'dynamic_models_bvmivam4',
            },
        ),
        migrations.CreateModel(
            name='Exn6Yuio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=20)),
                ('semester', models.CharField(max_length=20)),
                ('section', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'eXn6Yuio',
                'db_table': 'dynamic_models_exn6yuio',
            },
        ),
        migrations.CreateModel(
            name='Hxuwmrug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=20)),
                ('semester', models.CharField(max_length=20)),
                ('section', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'HXuWmRUG',
                'db_table': 'dynamic_models_hxuwmrug',
            },
        ),
        migrations.CreateModel(
            name='Kc2U06Xq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=20)),
                ('semester', models.CharField(max_length=20)),
                ('section', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'kC2U06xQ',
                'db_table': 'dynamic_models_kc2u06xq',
            },
        ),
        migrations.CreateModel(
            name='Kolf5N1X',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=20)),
                ('semester', models.CharField(max_length=20)),
                ('section', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'KoLf5n1x',
                'db_table': 'dynamic_models_kolf5n1x',
            },
        ),
        migrations.CreateModel(
            name='Oedmuufq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=20)),
                ('semester', models.CharField(max_length=20)),
                ('section', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'oEdmuUfQ',
                'db_table': 'dynamic_models_oedmuufq',
            },
        ),
        migrations.CreateModel(
            name='Phkppsda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'pHKpPsdA',
                'db_table': 'dynamic_models_phkppsda',
            },
        ),
        migrations.CreateModel(
            name='Svtekvia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=20)),
                ('semester', models.CharField(max_length=20)),
                ('section', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'SvTeKVia',
                'db_table': 'dynamic_models_svtekvia',
            },
        ),
        migrations.CreateModel(
            name='Swsr7Fe7',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abhilash', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=20)),
                ('semester', models.CharField(max_length=20)),
                ('section', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'sWsr7FE7',
                'db_table': 'dynamic_models_swsr7fe7',
            },
        ),
        migrations.CreateModel(
            name='Tzmacewy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newmodel', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=20)),
                ('semester', models.CharField(max_length=20)),
                ('section', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'TzmaCeWy',
                'db_table': 'dynamic_models_tzmacewy',
            },
        ),
        migrations.CreateModel(
            name='Vq9Claqk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=20)),
                ('semester', models.CharField(max_length=20)),
                ('section', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Vq9ClAQK',
                'db_table': 'dynamic_models_vq9claqk',
            },
        ),
        migrations.CreateModel(
            name='Vqiwbniz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'VQiwbNIz',
                'db_table': 'dynamic_models_vqiwbniz',
            },
        ),
        migrations.CreateModel(
            name='Xsjrvlfw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=20)),
                ('semester', models.CharField(max_length=20)),
                ('section', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'XsjRvLfW',
                'db_table': 'dynamic_models_xsjrvlfw',
            },
        ),
        migrations.CreateModel(
            name='Z5Dznk7M',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=20)),
                ('semester', models.CharField(max_length=20)),
                ('section', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'z5dzNk7M',
                'db_table': 'dynamic_models_z5dznk7m',
            },
        ),
        migrations.CreateModel(
            name='Zgrzrkdn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=20)),
                ('semester', models.CharField(max_length=20)),
                ('section', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'zgrzRKdn',
                'db_table': 'dynamic_models_zgrzrkdn',
            },
        ),
    ]
