# Generated by Django 3.0.5 on 2021-01-03 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_models', '0002_8qydqsrg_abhilash_abhilashs_bttbqvxm_bvmivam4_exn6yuio_hxuwmrug_kc2u06xq_kolf5n1x_oedmuufq_phkppsda_'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atped2Yw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=20)),
                ('semester', models.CharField(max_length=20)),
                ('section', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'AtPed2Yw',
                'db_table': 'dynamic_models_atped2yw',
            },
        ),
        migrations.CreateModel(
            name='Frmm88Oj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=20)),
                ('semester', models.CharField(max_length=20)),
                ('section', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'FrMM88oj',
                'db_table': 'dynamic_models_frmm88oj',
            },
        ),
        migrations.CreateModel(
            name='Iajj3Sgg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=20)),
                ('semester', models.CharField(max_length=20)),
                ('section', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'IAJj3SgG',
                'db_table': 'dynamic_models_iajj3sgg',
            },
        ),
        migrations.CreateModel(
            name='Lfc2Dg6S',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=20)),
                ('semester', models.CharField(max_length=20)),
                ('section', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Lfc2dG6s',
                'db_table': 'dynamic_models_lfc2dg6s',
            },
        ),
        migrations.CreateModel(
            name='Lgn79Wjx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=20)),
                ('semester', models.CharField(max_length=20)),
                ('section', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'LGN79WJx',
                'db_table': 'dynamic_models_lgn79wjx',
            },
        ),
        migrations.CreateModel(
            name='R9Kifzmq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=20)),
                ('semester', models.CharField(max_length=20)),
                ('section', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'r9kifZMQ',
                'db_table': 'dynamic_models_r9kifzmq',
            },
        ),
        migrations.CreateModel(
            name='Rgigcrhi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=20)),
                ('semester', models.CharField(max_length=20)),
                ('section', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'rGIgcrhi',
                'db_table': 'dynamic_models_rgigcrhi',
            },
        ),
        migrations.CreateModel(
            name='Tbbrfmbj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=20)),
                ('semester', models.CharField(max_length=20)),
                ('section', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'tbBRFMBJ',
                'db_table': 'dynamic_models_tbbrfmbj',
            },
        ),
        migrations.CreateModel(
            name='Tegskcdg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=20)),
                ('semester', models.CharField(max_length=20)),
                ('section', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'TEGSKcDG',
                'db_table': 'dynamic_models_tegskcdg',
            },
        ),
        migrations.CreateModel(
            name='Us9Sks0I',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=20)),
                ('semester', models.CharField(max_length=20)),
                ('section', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'us9SKS0I',
                'db_table': 'dynamic_models_us9sks0i',
            },
        ),
        migrations.CreateModel(
            name='V0Idwebv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=20)),
                ('semester', models.CharField(max_length=20)),
                ('section', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'v0IdWEBv',
                'db_table': 'dynamic_models_v0idwebv',
            },
        ),
    ]
