# Generated by Django 3.0.5 on 2021-01-03 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_models', '0003_atped2yw_frmm88oj_iajj3sgg_lfc2dg6s_lgn79wjx_r9kifzmq_rgigcrhi_tbbrfmbj_tegskcdg_us9sks0i_v0idwebv'),
    ]

    operations = [
        migrations.CreateModel(
            name='24D0Ah5G',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=20)),
                ('semester', models.CharField(max_length=20)),
                ('section', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': '24d0aH5G',
                'db_table': 'dynamic_models_24d0ah5g',
            },
        ),
        migrations.CreateModel(
            name='Ks7Cynsb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topics', models.CharField(max_length=100)),
                ('status', models.BooleanField(null=True)),
                ('completed_date', models.DateTimeField(null=True)),
            ],
            options={
                'verbose_name': 'kS7cynsB',
                'db_table': 'dynamic_models_ks7cynsb',
            },
        ),
        migrations.CreateModel(
            name='Ndnnduvm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topics', models.CharField(max_length=100)),
                ('status', models.BooleanField(null=True)),
                ('completed_date', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'NdnNDuvM',
                'db_table': 'dynamic_models_ndnnduvm',
            },
        ),
        migrations.CreateModel(
            name='Poralf4Q',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=20)),
                ('semester', models.CharField(max_length=20)),
                ('section', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'porALF4Q',
                'db_table': 'dynamic_models_poralf4q',
            },
        ),
        migrations.AlterField(
            model_name='fieldschema',
            name='data_type',
            field=models.CharField(choices=[('character', 'character'), ('text', 'text'), ('integer', 'integer'), ('float', 'float'), ('boolean', 'boolean'), ('date', 'date'), ('richtext', 'richtext')], editable=False, max_length=16),
        ),
    ]
