# Generated by Django 3.0.5 on 2021-01-06 12:39

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_models', '0004_auto_20210103_1816'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gqwhejbq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topics', models.CharField(max_length=100)),
                ('video_link', models.SlugField(null=True)),
                ('completed_date', models.DateTimeField(null=True)),
                ('discription', ckeditor.fields.RichTextField(null=True)),
            ],
            options={
                'verbose_name': 'GqWHeJBq',
                'db_table': 'dynamic_models_gqwhejbq',
            },
        ),
        migrations.CreateModel(
            name='Ki6Ykthw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topics', models.CharField(max_length=100)),
                ('status', models.BooleanField(null=True)),
                ('completed_date', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Ki6yKtHW',
                'db_table': 'dynamic_models_ki6ykthw',
            },
        ),
        migrations.CreateModel(
            name='Lc1Qfc1M',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topics', models.CharField(max_length=100)),
                ('status', models.BooleanField(null=True)),
                ('completed_date', models.DateTimeField(null=True)),
            ],
            options={
                'verbose_name': 'lc1Qfc1M',
                'db_table': 'dynamic_models_lc1qfc1m',
            },
        ),
        migrations.CreateModel(
            name='O1Lhr598',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topics', models.CharField(max_length=100)),
                ('status', models.BooleanField(null=True)),
                ('completed_date', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'O1LHr598',
                'db_table': 'dynamic_models_o1lhr598',
            },
        ),
        migrations.CreateModel(
            name='Qfsnafm6',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topics', models.CharField(max_length=100)),
                ('status', models.BooleanField(null=True)),
                ('completed_date', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'qFsNAFM6',
                'db_table': 'dynamic_models_qfsnafm6',
            },
        ),
        migrations.AlterField(
            model_name='fieldschema',
            name='data_type',
            field=models.CharField(choices=[('character', 'character'), ('text', 'text'), ('integer', 'integer'), ('float', 'float'), ('boolean', 'boolean'), ('date', 'date'), ('richtext', 'richtext'), ('url', 'url')], editable=False, max_length=16),
        ),
    ]
