# Generated by Django 3.0.5 on 2021-01-08 10:15

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_models', '0005_auto_20210106_1239'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ehpd05N0',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topics', models.CharField(max_length=100)),
                ('video_link', models.SlugField(null=True)),
                ('completed_date', models.DateTimeField(null=True)),
                ('discription', ckeditor.fields.RichTextField(null=True)),
            ],
            options={
                'verbose_name': 'eHPD05N0',
                'db_table': 'dynamic_models_ehpd05n0',
            },
        ),
        migrations.DeleteModel(
            name='24D0Ah5G',
        ),
        migrations.DeleteModel(
            name='8Qydqsrg',
        ),
        migrations.DeleteModel(
            name='Abhilash',
        ),
        migrations.DeleteModel(
            name='Abhilashs',
        ),
        migrations.DeleteModel(
            name='Atped2Yw',
        ),
        migrations.DeleteModel(
            name='Bttbqvxm',
        ),
        migrations.DeleteModel(
            name='Bvmivam4',
        ),
        migrations.DeleteModel(
            name='Exn6Yuio',
        ),
        migrations.DeleteModel(
            name='Frmm88Oj',
        ),
        migrations.DeleteModel(
            name='Gqwhejbq',
        ),
        migrations.DeleteModel(
            name='Hxuwmrug',
        ),
        migrations.DeleteModel(
            name='Iajj3Sgg',
        ),
        migrations.DeleteModel(
            name='Kc2U06Xq',
        ),
        migrations.DeleteModel(
            name='Ki6Ykthw',
        ),
        migrations.DeleteModel(
            name='Kolf5N1X',
        ),
        migrations.DeleteModel(
            name='Ks7Cynsb',
        ),
        migrations.DeleteModel(
            name='Lc1Qfc1M',
        ),
        migrations.DeleteModel(
            name='Lfc2Dg6S',
        ),
        migrations.DeleteModel(
            name='Lgn79Wjx',
        ),
        migrations.DeleteModel(
            name='Ndnnduvm',
        ),
        migrations.DeleteModel(
            name='O1Lhr598',
        ),
        migrations.DeleteModel(
            name='Oedmuufq',
        ),
        migrations.DeleteModel(
            name='Phkppsda',
        ),
        migrations.DeleteModel(
            name='Poralf4Q',
        ),
        migrations.DeleteModel(
            name='Qfsnafm6',
        ),
        migrations.DeleteModel(
            name='R9Kifzmq',
        ),
        migrations.DeleteModel(
            name='Rgigcrhi',
        ),
        migrations.DeleteModel(
            name='Svtekvia',
        ),
        migrations.DeleteModel(
            name='Swsr7Fe7',
        ),
        migrations.DeleteModel(
            name='Tbbrfmbj',
        ),
        migrations.DeleteModel(
            name='Tegskcdg',
        ),
        migrations.DeleteModel(
            name='Tzmacewy',
        ),
        migrations.DeleteModel(
            name='Us9Sks0I',
        ),
        migrations.DeleteModel(
            name='V0Idwebv',
        ),
        migrations.DeleteModel(
            name='Vq9Claqk',
        ),
        migrations.DeleteModel(
            name='Vqiwbniz',
        ),
        migrations.DeleteModel(
            name='Xsjrvlfw',
        ),
        migrations.DeleteModel(
            name='Z5Dznk7M',
        ),
        migrations.DeleteModel(
            name='Zgrzrkdn',
        ),
    ]
