# Generated by Django 3.0.5 on 2021-01-08 10:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Branch',
            },
        ),
        migrations.CreateModel(
            name='Modelnames',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('name', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Section',
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('name', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Semester',
            },
        ),
        migrations.CreateModel(
            name='newClasses',
            fields=[
                ('classId', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('className', models.CharField(max_length=50)),
                ('classSection', models.CharField(max_length=50)),
                ('classBranch', models.CharField(max_length=50)),
                ('classSemester', models.CharField(max_length=10)),
                ('createdDate', models.DateTimeField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Classes',
            },
        ),
    ]
