# Generated by Django 3.0.5 on 2020-11-18 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.DecimalField(decimal_places=0, max_digits=5)),
                ('topic', models.CharField(max_length=100)),
                ('status', models.BooleanField()),
            ],
            options={
                'verbose_name_plural': 'Computer Science',
            },
        ),
    ]
