# Generated by Django 3.0.5 on 2020-11-18 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.DecimalField(decimal_places=2, max_digits=5)),
                ('topic', models.CharField(max_length=100)),
                ('status', models.BooleanField()),
            ],
            options={
                'verbose_name_plural': 'Advanced Computer Architectures',
            },
        ),
        migrations.CreateModel(
            name='CC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.DecimalField(decimal_places=2, max_digits=5)),
                ('topic', models.CharField(max_length=100)),
                ('status', models.BooleanField()),
            ],
            options={
                'verbose_name_plural': 'Cloud Computing',
            },
        ),
        migrations.CreateModel(
            name='ML',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.DecimalField(decimal_places=2, max_digits=5)),
                ('topic', models.CharField(max_length=100)),
                ('status', models.BooleanField()),
            ],
            options={
                'verbose_name_plural': 'Machine Learning',
            },
        ),
        migrations.CreateModel(
            name='MlLab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.DecimalField(decimal_places=2, max_digits=5)),
                ('topic', models.CharField(max_length=100)),
                ('status', models.BooleanField()),
            ],
            options={
                'verbose_name_plural': 'Machine Learning Laboratory',
            },
        ),
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.DecimalField(decimal_places=2, max_digits=5)),
                ('topic', models.CharField(max_length=100)),
                ('status', models.BooleanField()),
            ],
            options={
                'verbose_name_plural': 'Project Work Phase–I + Project work Seminar',
            },
        ),
        migrations.CreateModel(
            name='SaN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.DecimalField(decimal_places=2, max_digits=5)),
                ('topic', models.CharField(max_length=100)),
                ('status', models.BooleanField()),
            ],
            options={
                'verbose_name_plural': 'Storage Area Network',
            },
        ),
        migrations.CreateModel(
            name='WebTechnology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.DecimalField(decimal_places=2, max_digits=5)),
                ('topic', models.CharField(max_length=100)),
                ('status', models.BooleanField()),
            ],
            options={
                'verbose_name_plural': 'Web Technology and its applications',
            },
        ),
        migrations.CreateModel(
            name='WtLab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.DecimalField(decimal_places=2, max_digits=5)),
                ('topic', models.CharField(max_length=100)),
                ('status', models.BooleanField()),
            ],
            options={
                'verbose_name_plural': 'Web Technology Laboratory with mini project',
            },
        ),
        migrations.DeleteModel(
            name='cse',
        ),
    ]
