# Generated by Django 3.0.5 on 2021-01-02 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0003_auto_20201119_0332'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modelnames',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelname', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='AcA',
        ),
        migrations.DeleteModel(
            name='CC',
        ),
        migrations.DeleteModel(
            name='ML',
        ),
        migrations.DeleteModel(
            name='MlLab',
        ),
        migrations.DeleteModel(
            name='project',
        ),
        migrations.DeleteModel(
            name='SaN',
        ),
        migrations.DeleteModel(
            name='WT',
        ),
        migrations.DeleteModel(
            name='WtLab',
        ),
    ]
